### ISSUE TITLE
Add event listeners

### ISSUE THREAD

**Issue by jcushman** [pakholeung37/vite-plugin-vue2-svg#3]
The webpack svg loader `vue-svg-loader` allows event handling on svgs in templates like this:

```
<MySVG @click="myClickEvent" @mouseover="myMouseoverEvent" />
```

I think it works through [this line](https://github.com/visualfanatic/vue-svg-loader/blob/dev/index.js#L16):

```
svg = svg.replace('<svg', '<svg v-on="$listeners"');
```

Could this loader add the same feature?

**Comment by pakholeung37** [comment]
close #5
