### ISSUE TITLE
[Feature Request] Bump SVGO to version 2

### ISSUE THREAD

**Issue by kingyue737** [pakholeung37/vite-plugin-vue2-svg#4]
SVGO v1 is deprecated. Is it possible to support SVGO 2?

**Comment by pakholeung37** [comment]
I will check for that, thanks for asking!

**Comment by pakholeung37** [comment]
@kingyue737 I could remember I use version 1.3 for some particular reasons. But I forget what it is... So it will stay the same

**Comment by pakholeung37** [comment]
pr #5
