### ISSUE TITLE
fix vue-template-compiler < 2.7

### ISSUE THREAD

**Issue by uyarn** [pakholeung37/vite-plugin-vue2-svg#6]
Hi, @pakholeung37 
As we know, vue 2.7 which enables developers use composition API in vue2 directly was released last week.
and vue-template-compiler 2.7 was released at the same time.

vue-template-compiler wasn't needed in 2.7 any longer

<img width="707" alt="image" src="https://user-images.githubusercontent.com/26377630/177290320-f5f4cd68-f06d-474b-a3a9-db373c2248b5.png">

However, project using `@vue/composition-api` is incompatible with vue 2.7+, so we need vue< 2.7 and vue-template-compiler < 2.7 as well.
Could you please modify the  vue-template-compiler version from '^2.6.0' to '~2.6.0'.  Otherwise, vue-template-compiler 2.7 would be installed and the warning that vue and vue-template-compiler are mismatch would appear: (

Cheers : )

**Comment by pakholeung37** [comment]
Do you use vite-plugin-vue2? Do it throw the same warning?

**Comment by uyarn** [comment]
> Do you use vite-plugin-vue2? Do it throw the same warning?

Yeap, but as you can see below,  `vue-template-compiler` is the peerDependency of `vite-plugin-vue2` so that the vue-template-compiler@2.7 wouldn't be installed once we install `vue-template-compiler` by ourself.
<img width="409" alt="image" src="https://user-images.githubusercontent.com/26377630/177453573-4fe231c2-85bf-4bfc-85b9-df7a8ee9992e.png">

**Comment by pakholeung37** [comment]
Would it be better for me to set peer dependencies either?

**Comment by uyarn** [comment]
> Would it be better for me to set peer dependencies either?

can't agree more :)  better alternative. and don't forget to set it as your devDep for develop as well :)
